version: "3"
services:
  fastapi_vue_template:
    image: fastapi_vue_template
    build:
      context: .
      dockerfile: dockerfiles/fastapi_vue_template.Dockerfile
    volumes:
      - ./data:/fastapi_vue_template/data
      - ./database.db:/db/db.db
    expose:
      - "8000"
    restart: unless-stopped
    command: uvicorn main:app --reload --host 0.0.0.0 --port 8000

  nginx:
    image: nginx:1.13.3
    ports:
      - "8000:8000"
    volumes:
      - ./nginx:/etc/nginx/conf.d
      - ./static:/static
    depends_on:
      - fastapi_vue_template
